const $=id=>document.getElementById(id);let config={},imageData="",timer=null,started=0;const kindNames={gateway:"网关往返",text:"LLM纯文本",vision:"LLM看图",image_edit:"CORE真实生图"};
function bytes(v){if(v<1024)return `${v} B`;if(v<1048576)return `${(v/1024).toFixed(1)} KB`;return `${(v/1048576).toFixed(2)} MB`}
function sec(v){return Number.isFinite(Number(v))?`${Number(v).toFixed(3)} s`:"—"}
async function api(url,opt={}){const r=await fetch(url,opt),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p}
function setRunning(on,label=""){document.querySelectorAll("[data-kind]").forEach(b=>b.disabled=on);$("liveClock").classList.toggle("running",on);$("liveClock").querySelector("span").textContent=on?label:"空闲";clearInterval(timer);if(on){started=performance.now();timer=setInterval(()=>$("liveClock").querySelector("strong").textContent=`${((performance.now()-started)/1000).toFixed(1)} s`,100)}else $("liveClock").querySelector("strong").textContent="0.0 s"}
function detailRow(k,v){return `<dt>${k}</dt><dd>${String(v??"—")}</dd>`}
function render(r){$("emptyResult").hidden=true;$("errorBox").hidden=true;$("result").hidden=false;$("resultSummary").textContent=`${kindNames[r.kind]}完成 · ${r.model||"无推理模型"}`;$("totalTime").textContent=sec(r.api_total_seconds);$("ttfb").textContent=sec(r.ttfb_seconds);$("download").textContent=sec(r.download_seconds);$("wall").textContent=sec(r.wall_seconds);$("status").textContent=r.http_status;$("payloadSize").textContent=`请求 ${bytes(r.request_bytes||0)} / 响应 ${bytes(r.response_bytes||0)}`;let html=detailRow("实际URL",r.url)+detailRow("模型",r.model||"—")+detailRow("源图尺寸",r.source_size?r.source_size.join(" × "):"—")+detailRow("请求尺寸",r.requested_size||"—")+detailRow("质量",r.quality||"—")+detailRow("Request ID",r.request_id||"网关未返回")+detailRow("Token用量",r.usage?.total_tokens??"—");$("details").innerHTML=html;$("outputPreview").hidden=!r.output_preview;$("outputPreview").textContent=r.output_preview||"";$("resultImage").hidden=!r.result_url;if(r.result_url)$("resultImage").src=`${r.result_url}?t=${Date.now()}`;loadHistory()}
function showError(e){$("emptyResult").hidden=true;$("result").hidden=true;$("errorBox").hidden=false;$("errorBox").textContent=e.message;$("resultSummary").textContent="测试失败"}
async function run(kind){if(kind==="image_edit"&&!$("confirmCost").checked){showError(new Error("请先勾选生图费用确认。"));return}setRunning(true,`${kindNames[kind]}进行中`);$("resultSummary").textContent="请求已发出，正在等待API返回…";$("errorBox").hidden=true;try{const r=await api("/api/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,image_data:imageData,prompt:$("prompt").value,confirm_cost:$("confirmCost").checked})});render(r)}catch(e){showError(e)}finally{setRunning(false)}}
async function loadHistory(){const p=await api("/api/history"),rows=p.history||[];$("historyBody").innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.finished_at).toLocaleTimeString()}</td><td>${kindNames[r.kind]}</td><td>${r.model||"—"}</td><td>${sec(r.ttfb_seconds)}</td><td>${sec(r.api_total_seconds)}</td><td>${bytes(r.request_bytes||0)}</td><td>成功</td></tr>`).join(""):`<tr><td colspan="7">暂无记录</td></tr>`}
async function init(){config=await api("/api/config");$("baseUrl").textContent=config.base_url;$("textModel").textContent=config.text_model;$("imageModel").textContent=config.image_model;$("quality").textContent=config.quality;$("preview").src=config.default_source;document.querySelectorAll("[data-kind]").forEach(b=>b.onclick=()=>run(b.dataset.kind));$("imageInput").onchange=e=>{const f=e.target.files[0];if(!f){imageData="";$("preview").src=config.default_source;$("imageInfo").textContent="当前使用内置测试图";return}if(f.size>25*1024*1024){showError(new Error("图片不能超过25MB"));e.target.value="";return}const reader=new FileReader();reader.onload=()=>{imageData=reader.result;$("preview").src=imageData;const img=new Image();img.onload=()=>$("imageInfo").textContent=`${f.name} · ${img.width}×${img.height} · ${bytes(f.size)}`;img.src=imageData};reader.readAsDataURL(f)};loadHistory()}
init().catch(showError);
